#!/bin/bash
# SecureMail Stack - Service Status & Access Guide

echo "=== SecureMail Services Status ==="
echo ""

# Backend Health
echo "📡 Backend (Orchestrator):"
if curl -s http://localhost:8080/health | grep -q "ok"; then
    echo "   ✅ Running on http://localhost:8080"
    echo "   ✅ Health: HEALTHY"
else
    echo "   ❌ Not responding on http://localhost:8080"
fi
echo ""

# API Endpoints
echo "🔌 API Endpoints:"
echo "   POST   /api/v1/scan-upload          - Rule-based scan upload"
echo "   POST   /api/v1/scan-upload-llm      - LLM deep-dive scan upload"
echo "   POST   /api/v1/scan-history         - Save scan result to PostgreSQL"
echo "   GET    /api/v1/scan-history         - Fetch scan history from PostgreSQL"
echo ""

# Frontend
echo "🎨 Frontend (Vite):"
echo "   ✅ Running on http://localhost:5173"
echo "   📄 Route: / (Dashboard)"
echo "   📧 Route: /scanner (Email Scanner)"
echo ""

# Database
echo "🗄️  Database (PostgreSQL):"
echo "   Host: localhost:5432"
echo "   Database: securemail"
echo "   User: securemail"
echo "   Table: scan_history (stores all scan results)"
echo ""

echo "=== How to Use ==="
echo ""
echo "1️⃣  Open browser: http://localhost:5173"
echo "2️⃣  Click 'Check Email' button (navigate to Scanner tab)"
echo "3️⃣  Upload a .eml email file (drag-drop or browse)"
echo "4️⃣  Choose scan mode:"
echo "    • Rule-Based: Fast security rules evaluation"
echo "    • LLM Deep Dive: AI-powered detailed analysis"
echo "5️⃣  Click 'Scan Email'"
echo "6️⃣  View results in real-time panel"
echo "7️⃣  Results auto-save to PostgreSQL"
echo "8️⃣  Dashboard displays historical metrics"
echo ""

echo "=== Quick Start Commands ==="
echo ""
echo "# Start backend (if not running):"
echo "cd /home/passla1/Desktop/SecureMail"
echo "source .venv/bin/activate"
echo "python orchestra/main.py"
echo ""
echo "# Start frontend (if not running):"
echo "cd /home/passla1/Desktop/SecureMail/UI-UX"
echo "npx vite  # or: npm run dev"
echo ""

echo "=== Troubleshooting ==="
echo ""
echo "❌ 'npm run dev' fails with package.json error?"
echo "   → Solution: Run 'npx vite' from UI-UX directory instead"
echo ""
echo "❌ NetworkError when fetching resource?"
echo "   → Solution: Ensure both backend (port 8080) and frontend (port 5173) are running"
echo "   → Check: curl http://localhost:8080/health"
echo ""
echo "❌ Scans not saving to PostgreSQL?"
echo "   → Check orchestrator logs for error messages"
echo "   → Verify PostgreSQL is running: psql -d securemail -c 'SELECT * FROM scan_history;'"
echo ""

echo "=== Architecture ==="
echo ""
echo "Frontend (Vite/React)"
echo "     ↓"
echo "     → POST /api/v1/scan-upload-llm (multipart file upload)"
echo "     ↓"
echo "Backend (FastAPI/Python)"
echo "     ↓"
echo "     → Process scan (LLM mode)"
echo "     ↓"
echo "     → Return ScanResponse"
echo "     ↓"
echo "Frontend receives response"
echo "     ↓"
echo "     → POST /api/v1/scan-history (save to DB)"
echo "     ↓"
echo "Backend saves to PostgreSQL"
echo "     ↓"
echo "     → Return SUCCESS + UUID"
echo "     ↓"
echo "Display results in UI"
echo ""
